spring:
  application:
    name: kafka-replay

mock:
  persistence:
    type:
    folder:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group: mocktail-kafka-replay
  topics: "topic-a,\
    topic-b,\
    topic-c,\
    topic-d"
